# Практика

## Определение вероятности. События

Требуется сгенерировать необходимые выборки и произвести по ним расчеты

### Задача 1
Брошено две монеты. Найти вероятность того, что монеты выпали разными сторонами

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as sts
import random

In [2]:
n = 1000000
df = pd.DataFrame(columns = ["coin1", "coin2"])
coin1 = sts.bernoulli(.5) # Бернули для монеты 1
coin2 = sts.bernoulli(.5) # Бернули для монеты 2
df["coin1"] = coin1.rvs(n) 
df["coin2"] = coin2.rvs(n)
p = len(df[df["coin1"]!=df["coin2"]])/df.shape[0]
p #=вероятность того, что монеты выпали разными сторонами 

0.501057

### Задача 2
Брошено три монеты. Описать множество всех элементарных событий. Найти вероятности следующих событий:


1.   A = {не выпало ни одного герба}
2.   B = {выпало четное число гербов}
3.   C = {на третьей монете выпал герб}


In [4]:
#количество подбрасывания 3х монет
# 0 - Орел, 1 - Решка
N = 100000
count_A = 0
count_B = 0
count_C = 0
B1 = [random.choice(range(0,2)) for i in range(N)] #подбрасывание первой монеты
B2 = [random.choice(range(0,2)) for i in range(N)] #подбрасывание второй монеты
B3 = [random.choice(range(0,2)) for i in range(N)] #подбрасывание третьей монеты
#Создаем цикл и проверяем условия
for i in range(N):
  if B1[i]== 1 and B2[i]==1 and B3[i]==1: #все Решка
    count_A += 1 #прибавляем в событие А
  if (B1[i]==0 and B2[i]==0 and B3[i]==1) or (B1[i]==0 and B3[i]==0 and B2[i]==1) or (B2[i]== 0 and B3[i]==0 and B1[i]==1):
    count_B += 1 #прибавляем в событие В
  if B3[i] == 0:
    count_C += 1 #прибавляем в событие С

#print(count_A,'\n',count_B,'\n',count_C)
print('вероятность, не выпало ни одного герба A =', count_A/N)
print('вероятность, выпало четное число гербов B =', count_B/N)
print('вероятность, на третьей монете выпал герб C =', count_C/N)
all_var = np.unique([B1, B2, B3], axis=1)
print('\nВозможные варианты событий: \n', all_var[0],'\n', all_var[1], '\n', all_var[2])

вероятность, не выпало ни одного герба A = 0.12365
вероятность, выпало четное число гербов B = 0.37735
вероятность, на третьей монете выпал герб C = 0.50124

Возможные варианты событий: 
 [0 0 0 0 1 1 1 1] 
 [0 0 1 1 0 0 1 1] 
 [0 1 0 1 0 1 0 1]


Предлагается также решить задачи: 

### Задача 3
Из двух претендентов E и L на ответственную должность три члена комиссии должны отобрать одного. Каждый член комиссии должен указать либо одного достойного, либо забраковать обоих. Претендент считается выбранным, если он был признана достойным хотя бы двумя членами комиссии.
Найти вероятность событий:

A = {рекомендован L}, B = {рекомендован E}


In [5]:
#число испытаний
N = 100000
E = 0
L = 0
# каждый член комисии может поставить 0 1 или 2
# 1 - рекомендован Е
# 2 - рекомендован L 
# 0 - ни кто не рекомендован
B1 = [random.choice(range(0,3)) for i in range(N)]
B2 = [random.choice(range(0,3)) for i in range(N)]
B3 = [random.choice(range(0,3)) for i in range(N)]
#делаем цикл и сравниваем 
for i in range(N):
  if (B1[i]==1 and B2[i]==1) or (B1[i]==1 and B3[i]==1) or (B2[i]==1 and B3[i]==1):
    E += 1
  if (B1[i]== 2 and B2[i]==2) or (B1[i]==2 and B3[i]==2) or (B2[i]==2 and B3[i]==2):
    L += 1
print('вероятность, рекомендован L =', E/N)
print('вероятность, рекомендован E =', L/N)

вероятность, рекомендован L = 0.25855
вероятность, рекомендован E = 0.26025


### Задача 4
Брошено две игральных кости. Описать множество элементарных событий. Найти вероятности событий:

A = {вышло две "шестерки"}

B = {сумма выпавших очков не меньше 11}

C = {не выпала ни одна "шестерка"}

In [6]:
#число испытаний
N = 100000
A=0
B=0
C=0
dice1 = [random.choice(range(1,7)) for i in range(N)] #выпавшее число на первом кубике
dice2 = [random.choice(range(1,7)) for i in range(N)] #выпавшее число на втором кубике
#делаем цикл и сравниваем 
for i in range(N):
    if dice1[i]==6 and dice2[i] ==6:
        A+=1
    if dice1[i]+dice2[i] >=11:
        B+=1
    if dice1[i]!=6 and dice2[i]!=6:
        C+=1
#print(A,'\n',B,'\n',C)
print('вероятность, вышло две "шестерки" =', A/N)
print('вероятность, сумма выпавших очков не меньше =', B/N)
print('вероятность, не выпала ни одна "шестерка"', C/N)
all_var = np.unique([dice1, dice2], axis=1)
print('\nВозможные варианты событий: \n', all_var[0],'\n', all_var[1])

вероятность, вышло две "шестерки" = 0.02799
вероятность, сумма выпавших очков не меньше = 0.08264
вероятность, не выпала ни одна "шестерка" 0.69599

Возможные варианты событий: 
 [1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6] 
 [1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6]


## Вероятность суммы событий

### Задача 5
Брошены две игральные кости. Найти вероятность события D = {выпала хотя бы одна шестёрка}


In [ ]:
n=10000
values1 = []
values2 = []

for x in range(n):
    values1.append (np.random.randint(1, 7))
    values2.append (np.random.randint(1, 7))
         
df = pd.DataFrame(zip(values1, values2 ),columns = ["cub1","cub2"] ) 

print (df)

print ('выпала хотя бы одна шестёрка',\
       df [((df.cub1 ==6)&(df.cub2 !=6))|((df.cub1 !=6)&(df.cub2 ==6))|((df.cub1 ==6)&(df.cub2 ==6)) ].shape[0]/n)

      cub1  cub2
0        1     5
1        1     3
2        4     4
3        5     3
4        6     4
...    ...   ...
9995     4     6
9996     4     3
9997     4     4
9998     1     1
9999     2     6

[10000 rows x 2 columns]
выпала хотя бы одна шестёрка 0.3045


Предлагается также решить задачи: 

### Задача 6
В телефонном номере три последние цифры стерлись. Считая, что все возможные значения стершихся цифр равновероятны, найти вероятность событий:

A = {Стерлись различные цифры},

B = {Стерлись одинаковые цифры},

C = {Среди стершихся цифр хотя бы две совпадают},

D = {Среди стершихся цифр хотя бы две различны}


In [ ]:
n=100000
num1 = []
num2 = []
num3 = []

for x in range(n):
    num1.append (np.random.randint(0, 10))
    num2.append (np.random.randint(0, 10))
    num3.append (np.random.randint(0, 10))    
df = pd.DataFrame(zip(num1, num2, num3 ), columns = ["num1","num2", "num3"] ) 

print (df)

print ('Стерлись различные цифры',\
       df [(df.num1 != df.num2)& (df.num1 != df.num3)& (df.num2 != df.num3)].shape[0]/n)
print ('Стерлись одинаковые цифры',\
       df [(df.num1 == df.num2)& (df.num1 == df.num3)& (df.num2 == df.num3)].shape[0]/n )
print ('Среди стершихся цифр хотя бы две совпадают',\
       df [(df.num1 == df.num2)|(df.num1 == df.num3)|(df.num2 == df.num3)].shape[0]/n )
print ('Среди стершихся цифр хотя бы две различны',\
       df [(df.num1 != df.num2)| (df.num1 != df.num3)|(df.num2 != df.num3)].shape[0]/n )

       num1  num2  num3
0         9     3     2
1         9     5     3
2         7     1     3
3         5     8     6
4         0     0     5
...     ...   ...   ...
99995     4     2     6
99996     5     5     7
99997     8     3     3
99998     4     5     8
99999     3     3     6

[100000 rows x 3 columns]
Стерлись различные цифры 0.71956
Стерлись одинаковые цифры 0.00973
Среди стершихся цифр хотя бы две совпадают 0.28044
Среди стершихся цифр хотя бы две различны 0.99027


## Случайные величины

### Задача 7
В лотерее имеется 10 билетов, из которых один выигрышный. Размер выигрыша 10 ден. ед.; стоимость билета 1 ден ед. Найти закон распределения случайной величины X, равной чистому выигрышу участника лотереи, который вытаскивает билет первым.

Предлагается также решить задачу: 

### Задача 8
Брошены две игральные кости. Найти закон распределения случайной величины $X$, равной сумме выпавших очков. Найти вероятности событий ${X <= 4}$, ${X > 4}$

In [ ]:
n=10000
values = []
for x in range(n):
    values.append(np.random.randint(1, 7) + np.random.randint(1, 7))
df = pd.DataFrame(values) 

print(df)
print ('вероятности событий  𝑋<=4 ', df [df[0] <= 4 ].shape[0]/n)
print ('вероятности событий  𝑋>4 ', df [df[0] > 4 ].shape[0]/n)

       0
0      3
1     11
2      7
3     12
4      3
...   ..
9995  11
9996   9
9997   6
9998   3
9999   9

[10000 rows x 1 columns]
вероятности событий  𝑋<=4  0.171
вероятности событий  𝑋>4  0.829


## Условные вероятности

### Задача 9
Из колоды (36 карт) вынимают последовательно без возвращения две карты. Найти вероятность того, что первой картой была шестерка, а второй — семерка. Найти условную вероятность того же события при условии, что обе карты бубновой масти.


In [7]:
#Создадим колоду
suit = ['Бубны', 'Червы', 'Трефы', 'Пики']
card = ['6', '7', '8', '9', '10', 'Валет', 'Дама', 'Король', 'Туз']
cards = []
for i in range(len(card)):
  cards.append(f'{card[i]} {suit[0]}')
  cards.append(f'{card[i]} {suit[1]}')
  cards.append(f'{card[i]} {suit[2]}')
  cards.append(f'{card[i]} {suit[3]}')
len(cards)

36

In [9]:
N=100000
A=0 
B=0
C=0
# создаем цикл
i=0
while i<N:
    i+=1
    cards_old=cards.copy()
    x1=random.choice(cards) # тянем первую карту
    cards_old.remove(x1)
    cards_new = cards_old.copy()
    x2=random.choice(cards_new) # тянем вторую карту
    if x1.startswith('6')==True and x2.startswith('7')==True: # проверяем что первая карта 6 и втроая 7 
        #и считаем число таких исходов
        A+=1
    
    # найдем количество события В
    if x1.endswith('Бубны')==True and x2.endswith('Бубны')==True:
        B+=1
    #Найдем вероятность что первой картой была 6,а второй — 7 
    #при условии, что обе карты бубновой масти
    if x1=='6 Бубны' and x2=='7 Бубны':
        C+=1

#
#print(A,B)
print('Вероятность события что первой картой была 6, а второй — 7 =', A/N)
print('Вероятность события  обе карты бубновой масти =', B/N)
#Услованя вероятность это отношнние вероятностьей АВ по отношение к вероятности В
#В нашем случаии это событие С когда 6 и 7 бубны
P=(C/N)#/(B/N)
print("""Услованя вероятность что первой картой была шестерка,
а второй — семерка при условии, что обе карты бубновой масти =""", P)

Вероятность события что первой картой была 6, а второй — 7 = 0.01272
Вероятность события  обе карты бубновой масти = 0.0571
Услованя вероятность что первой картой была шестерка,
а второй — семерка при условии, что обе карты бубновой масти = 0.00081


Предлагается также решить задачу: 

### Задача 10
Из урны, содержащей два белых и три черных шара, последовательно извлекают два шара; вынутые шары не возвращаются. Если первый шар оказался черным, то перед вторым извлечением в урну добавляют белый шар. В противном случае состав оставшихся шаров не меняют. Найти вероятности событий:

$A$ = {извлечены два белых шара},

$B$ = {извлечены два черных шара}

Указание. Пусть событие $C_1$ = {первый шар белый}, событие $C_2$ = {второй шар белый}. Тогда $A = C_1C_2$, $B = \overline C_1 \overline C_2$ 